// Generated by CoffeeScript 1.6.1
(function() {

  exports.game = function(app) {
    return function(req, res) {
      if (req.session.username == null) {
        res.redirect('/');
      }
      return res.render("game", {
        username: req.session.username
      });
    };
  };

}).call(this);
