// Generated by CoffeeScript 1.6.1
(function() {

  exports.index = function(req, res) {
    req.session.machin = "bidule";
    if ("username" in req.session) {
      res.redirect('/game');
    }
    return res.render("index", {
      title: "Hamil"
    });
  };

}).call(this);
